//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("THACOModel", "FK_tblBaoCaoSX_tblSanPham", "tblSanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(THACO.DAL.tblSanPham), "tblBaoCaoSX", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(THACO.DAL.tblBaoCaoSX), true)]
[assembly: EdmRelationshipAttribute("THACOModel", "FK_tblChuyen_tblDonVi", "tblDonVi", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(THACO.DAL.tblDonVi), "tblChuyen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(THACO.DAL.tblChuyen), true)]
[assembly: EdmRelationshipAttribute("THACOModel", "FK_tblLoaiSP_tblDonVi", "tblDonVi", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(THACO.DAL.tblDonVi), "tblLoaiSP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(THACO.DAL.tblLoaiSP), true)]
[assembly: EdmRelationshipAttribute("THACOModel", "FK_tblKeHoachSX_tblSanPham", "tblSanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(THACO.DAL.tblSanPham), "tblKeHoachSX", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(THACO.DAL.tblKeHoachSX), true)]
[assembly: EdmRelationshipAttribute("THACOModel", "FK_tblKetQuaSX_tblSanPham", "tblSanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(THACO.DAL.tblSanPham), "tblKetQuaSX", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(THACO.DAL.tblKetQuaSX), true)]
[assembly: EdmRelationshipAttribute("THACOModel", "FK_tblSanPham_tblLoaiSP", "tblLoaiSP", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(THACO.DAL.tblLoaiSP), "tblSanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(THACO.DAL.tblSanPham), true)]
[assembly: EdmRelationshipAttribute("THACOModel", "FK_tblTaoMa_tblSanPham", "tblSanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(THACO.DAL.tblSanPham), "tblTaoMa", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(THACO.DAL.tblTaoMa), true)]

#endregion

namespace THACO.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class THACOEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new THACOEntities object using the connection string found in the 'THACOEntities' section of the application configuration file.
        /// </summary>
        public THACOEntities() : base("name=THACOEntities", "THACOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new THACOEntities object.
        /// </summary>
        public THACOEntities(string connectionString) : base(connectionString, "THACOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new THACOEntities object.
        /// </summary>
        public THACOEntities(EntityConnection connection) : base(connection, "THACOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblBaoCaoSX> tblBaoCaoSXes
        {
            get
            {
                if ((_tblBaoCaoSXes == null))
                {
                    _tblBaoCaoSXes = base.CreateObjectSet<tblBaoCaoSX>("tblBaoCaoSXes");
                }
                return _tblBaoCaoSXes;
            }
        }
        private ObjectSet<tblBaoCaoSX> _tblBaoCaoSXes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblChuyen> tblChuyens
        {
            get
            {
                if ((_tblChuyens == null))
                {
                    _tblChuyens = base.CreateObjectSet<tblChuyen>("tblChuyens");
                }
                return _tblChuyens;
            }
        }
        private ObjectSet<tblChuyen> _tblChuyens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblDonVi> tblDonVis
        {
            get
            {
                if ((_tblDonVis == null))
                {
                    _tblDonVis = base.CreateObjectSet<tblDonVi>("tblDonVis");
                }
                return _tblDonVis;
            }
        }
        private ObjectSet<tblDonVi> _tblDonVis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblKeHoachSX> tblKeHoachSXes
        {
            get
            {
                if ((_tblKeHoachSXes == null))
                {
                    _tblKeHoachSXes = base.CreateObjectSet<tblKeHoachSX>("tblKeHoachSXes");
                }
                return _tblKeHoachSXes;
            }
        }
        private ObjectSet<tblKeHoachSX> _tblKeHoachSXes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblKetQuaSX> tblKetQuaSXes
        {
            get
            {
                if ((_tblKetQuaSXes == null))
                {
                    _tblKetQuaSXes = base.CreateObjectSet<tblKetQuaSX>("tblKetQuaSXes");
                }
                return _tblKetQuaSXes;
            }
        }
        private ObjectSet<tblKetQuaSX> _tblKetQuaSXes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblLoaiSP> tblLoaiSPs
        {
            get
            {
                if ((_tblLoaiSPs == null))
                {
                    _tblLoaiSPs = base.CreateObjectSet<tblLoaiSP>("tblLoaiSPs");
                }
                return _tblLoaiSPs;
            }
        }
        private ObjectSet<tblLoaiSP> _tblLoaiSPs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSanPham> tblSanPhams
        {
            get
            {
                if ((_tblSanPhams == null))
                {
                    _tblSanPhams = base.CreateObjectSet<tblSanPham>("tblSanPhams");
                }
                return _tblSanPhams;
            }
        }
        private ObjectSet<tblSanPham> _tblSanPhams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTaoMa> tblTaoMas
        {
            get
            {
                if ((_tblTaoMas == null))
                {
                    _tblTaoMas = base.CreateObjectSet<tblTaoMa>("tblTaoMas");
                }
                return _tblTaoMas;
            }
        }
        private ObjectSet<tblTaoMa> _tblTaoMas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblThamSo> tblThamSoes
        {
            get
            {
                if ((_tblThamSoes == null))
                {
                    _tblThamSoes = base.CreateObjectSet<tblThamSo>("tblThamSoes");
                }
                return _tblThamSoes;
            }
        }
        private ObjectSet<tblThamSo> _tblThamSoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUser> tblUsers
        {
            get
            {
                if ((_tblUsers == null))
                {
                    _tblUsers = base.CreateObjectSet<tblUser>("tblUsers");
                }
                return _tblUsers;
            }
        }
        private ObjectSet<tblUser> _tblUsers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblBaoCaoSXes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblBaoCaoSXes(tblBaoCaoSX tblBaoCaoSX)
        {
            base.AddObject("tblBaoCaoSXes", tblBaoCaoSX);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblChuyens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblChuyens(tblChuyen tblChuyen)
        {
            base.AddObject("tblChuyens", tblChuyen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblDonVis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblDonVis(tblDonVi tblDonVi)
        {
            base.AddObject("tblDonVis", tblDonVi);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblKeHoachSXes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblKeHoachSXes(tblKeHoachSX tblKeHoachSX)
        {
            base.AddObject("tblKeHoachSXes", tblKeHoachSX);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblKetQuaSXes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblKetQuaSXes(tblKetQuaSX tblKetQuaSX)
        {
            base.AddObject("tblKetQuaSXes", tblKetQuaSX);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblLoaiSPs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblLoaiSPs(tblLoaiSP tblLoaiSP)
        {
            base.AddObject("tblLoaiSPs", tblLoaiSP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSanPhams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSanPhams(tblSanPham tblSanPham)
        {
            base.AddObject("tblSanPhams", tblSanPham);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTaoMas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTaoMas(tblTaoMa tblTaoMa)
        {
            base.AddObject("tblTaoMas", tblTaoMa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblThamSoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblThamSoes(tblThamSo tblThamSo)
        {
            base.AddObject("tblThamSoes", tblThamSo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsers(tblUser tblUser)
        {
            base.AddObject("tblUsers", tblUser);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="sNgay">No Metadata Documentation available.</param>
        public ObjectResult<KetQua_Ngay_Result> KetQua_Ngay(Nullable<global::System.DateTime> sNgay)
        {
            ObjectParameter sNgayParameter;
            if (sNgay.HasValue)
            {
                sNgayParameter = new ObjectParameter("sNgay", sNgay);
            }
            else
            {
                sNgayParameter = new ObjectParameter("sNgay", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<KetQua_Ngay_Result>("KetQua_Ngay", sNgayParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblBaoCaoSX")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblBaoCaoSX : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblBaoCaoSX object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblBaoCaoSX CreatetblBaoCaoSX(global::System.Int32 id)
        {
            tblBaoCaoSX tblBaoCaoSX = new tblBaoCaoSX();
            tblBaoCaoSX.ID = id;
            return tblBaoCaoSX;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SanPhamID
        {
            get
            {
                return _SanPhamID;
            }
            set
            {
                OnSanPhamIDChanging(value);
                ReportPropertyChanging("SanPhamID");
                _SanPhamID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SanPhamID");
                OnSanPhamIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SanPhamID;
        partial void OnSanPhamIDChanging(Nullable<global::System.Int32> value);
        partial void OnSanPhamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Ngay
        {
            get
            {
                return _Ngay;
            }
            set
            {
                OnNgayChanging(value);
                ReportPropertyChanging("Ngay");
                _Ngay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ngay");
                OnNgayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Ngay;
        partial void OnNgayChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThucHien
        {
            get
            {
                return _ThucHien;
            }
            set
            {
                OnThucHienChanging(value);
                ReportPropertyChanging("ThucHien");
                _ThucHien = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThucHien");
                OnThucHienChanged();
            }
        }
        private global::System.String _ThucHien;
        partial void OnThucHienChanging(global::System.String value);
        partial void OnThucHienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KeHoach
        {
            get
            {
                return _KeHoach;
            }
            set
            {
                OnKeHoachChanging(value);
                ReportPropertyChanging("KeHoach");
                _KeHoach = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KeHoach");
                OnKeHoachChanged();
            }
        }
        private global::System.String _KeHoach;
        partial void OnKeHoachChanging(global::System.String value);
        partial void OnKeHoachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiLe
        {
            get
            {
                return _TiLe;
            }
            set
            {
                OnTiLeChanging(value);
                ReportPropertyChanging("TiLe");
                _TiLe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiLe");
                OnTiLeChanged();
            }
        }
        private global::System.String _TiLe;
        partial void OnTiLeChanging(global::System.String value);
        partial void OnTiLeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblBaoCaoSX_tblSanPham", "tblSanPham")]
        public tblSanPham tblSanPham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblBaoCaoSX_tblSanPham", "tblSanPham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblBaoCaoSX_tblSanPham", "tblSanPham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblSanPham> tblSanPhamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblBaoCaoSX_tblSanPham", "tblSanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblSanPham>("THACOModel.FK_tblBaoCaoSX_tblSanPham", "tblSanPham", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblChuyen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblChuyen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblChuyen object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblChuyen CreatetblChuyen(global::System.Int32 id)
        {
            tblChuyen tblChuyen = new tblChuyen();
            tblChuyen.ID = id;
            return tblChuyen;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaChuyen
        {
            get
            {
                return _MaChuyen;
            }
            set
            {
                OnMaChuyenChanging(value);
                ReportPropertyChanging("MaChuyen");
                _MaChuyen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaChuyen");
                OnMaChuyenChanged();
            }
        }
        private global::System.String _MaChuyen;
        partial void OnMaChuyenChanging(global::System.String value);
        partial void OnMaChuyenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenChuyen
        {
            get
            {
                return _TenChuyen;
            }
            set
            {
                OnTenChuyenChanging(value);
                ReportPropertyChanging("TenChuyen");
                _TenChuyen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenChuyen");
                OnTenChuyenChanged();
            }
        }
        private global::System.String _TenChuyen;
        partial void OnTenChuyenChanging(global::System.String value);
        partial void OnTenChuyenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DonViID
        {
            get
            {
                return _DonViID;
            }
            set
            {
                OnDonViIDChanging(value);
                ReportPropertyChanging("DonViID");
                _DonViID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DonViID");
                OnDonViIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DonViID;
        partial void OnDonViIDChanging(Nullable<global::System.Int32> value);
        partial void OnDonViIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenTiengAnh
        {
            get
            {
                return _TenTiengAnh;
            }
            set
            {
                OnTenTiengAnhChanging(value);
                ReportPropertyChanging("TenTiengAnh");
                _TenTiengAnh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenTiengAnh");
                OnTenTiengAnhChanged();
            }
        }
        private global::System.String _TenTiengAnh;
        partial void OnTenTiengAnhChanging(global::System.String value);
        partial void OnTenTiengAnhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThuTu
        {
            get
            {
                return _ThuTu;
            }
            set
            {
                OnThuTuChanging(value);
                ReportPropertyChanging("ThuTu");
                _ThuTu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThuTu");
                OnThuTuChanged();
            }
        }
        private Nullable<global::System.Int32> _ThuTu;
        partial void OnThuTuChanging(Nullable<global::System.Int32> value);
        partial void OnThuTuChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblChuyen_tblDonVi", "tblDonVi")]
        public tblDonVi tblDonVi
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblDonVi>("THACOModel.FK_tblChuyen_tblDonVi", "tblDonVi").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblDonVi>("THACOModel.FK_tblChuyen_tblDonVi", "tblDonVi").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblDonVi> tblDonViReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblDonVi>("THACOModel.FK_tblChuyen_tblDonVi", "tblDonVi");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblDonVi>("THACOModel.FK_tblChuyen_tblDonVi", "tblDonVi", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblDonVi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblDonVi : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblDonVi object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblDonVi CreatetblDonVi(global::System.Int32 id)
        {
            tblDonVi tblDonVi = new tblDonVi();
            tblDonVi.ID = id;
            return tblDonVi;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaDV
        {
            get
            {
                return _MaDV;
            }
            set
            {
                OnMaDVChanging(value);
                ReportPropertyChanging("MaDV");
                _MaDV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaDV");
                OnMaDVChanged();
            }
        }
        private global::System.String _MaDV;
        partial void OnMaDVChanging(global::System.String value);
        partial void OnMaDVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DonVi
        {
            get
            {
                return _DonVi;
            }
            set
            {
                OnDonViChanging(value);
                ReportPropertyChanging("DonVi");
                _DonVi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DonVi");
                OnDonViChanged();
            }
        }
        private global::System.String _DonVi;
        partial void OnDonViChanging(global::System.String value);
        partial void OnDonViChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblChuyen_tblDonVi", "tblChuyen")]
        public EntityCollection<tblChuyen> tblChuyens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblChuyen>("THACOModel.FK_tblChuyen_tblDonVi", "tblChuyen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblChuyen>("THACOModel.FK_tblChuyen_tblDonVi", "tblChuyen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblLoaiSP_tblDonVi", "tblLoaiSP")]
        public EntityCollection<tblLoaiSP> tblLoaiSPs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblLoaiSP>("THACOModel.FK_tblLoaiSP_tblDonVi", "tblLoaiSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblLoaiSP>("THACOModel.FK_tblLoaiSP_tblDonVi", "tblLoaiSP", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblKeHoachSX")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblKeHoachSX : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblKeHoachSX object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblKeHoachSX CreatetblKeHoachSX(global::System.Int32 id)
        {
            tblKeHoachSX tblKeHoachSX = new tblKeHoachSX();
            tblKeHoachSX.ID = id;
            return tblKeHoachSX;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SanPhamID
        {
            get
            {
                return _SanPhamID;
            }
            set
            {
                OnSanPhamIDChanging(value);
                ReportPropertyChanging("SanPhamID");
                _SanPhamID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SanPhamID");
                OnSanPhamIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SanPhamID;
        partial void OnSanPhamIDChanging(Nullable<global::System.Int32> value);
        partial void OnSanPhamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Ngay
        {
            get
            {
                return _Ngay;
            }
            set
            {
                OnNgayChanging(value);
                ReportPropertyChanging("Ngay");
                _Ngay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ngay");
                OnNgayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Ngay;
        partial void OnNgayChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLuong
        {
            get
            {
                return _SoLuong;
            }
            set
            {
                OnSoLuongChanging(value);
                ReportPropertyChanging("SoLuong");
                _SoLuong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoLuong");
                OnSoLuongChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLuong;
        partial void OnSoLuongChanging(Nullable<global::System.Int32> value);
        partial void OnSoLuongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdate;
        partial void OnLastUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LastUpdateBy
        {
            get
            {
                return _LastUpdateBy;
            }
            set
            {
                OnLastUpdateByChanging(value);
                ReportPropertyChanging("LastUpdateBy");
                _LastUpdateBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateBy");
                OnLastUpdateByChanged();
            }
        }
        private Nullable<global::System.Int32> _LastUpdateBy;
        partial void OnLastUpdateByChanging(Nullable<global::System.Int32> value);
        partial void OnLastUpdateByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblKeHoachSX_tblSanPham", "tblSanPham")]
        public tblSanPham tblSanPham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblKeHoachSX_tblSanPham", "tblSanPham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblKeHoachSX_tblSanPham", "tblSanPham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblSanPham> tblSanPhamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblKeHoachSX_tblSanPham", "tblSanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblSanPham>("THACOModel.FK_tblKeHoachSX_tblSanPham", "tblSanPham", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblKetQuaSX")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblKetQuaSX : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblKetQuaSX object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblKetQuaSX CreatetblKetQuaSX(global::System.Int32 id)
        {
            tblKetQuaSX tblKetQuaSX = new tblKetQuaSX();
            tblKetQuaSX.ID = id;
            return tblKetQuaSX;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SanPhamID
        {
            get
            {
                return _SanPhamID;
            }
            set
            {
                OnSanPhamIDChanging(value);
                ReportPropertyChanging("SanPhamID");
                _SanPhamID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SanPhamID");
                OnSanPhamIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SanPhamID;
        partial void OnSanPhamIDChanging(Nullable<global::System.Int32> value);
        partial void OnSanPhamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgaySX
        {
            get
            {
                return _NgaySX;
            }
            set
            {
                OnNgaySXChanging(value);
                ReportPropertyChanging("NgaySX");
                _NgaySX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgaySX");
                OnNgaySXChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgaySX;
        partial void OnNgaySXChanging(Nullable<global::System.DateTime> value);
        partial void OnNgaySXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaBarcode
        {
            get
            {
                return _MaBarcode;
            }
            set
            {
                OnMaBarcodeChanging(value);
                ReportPropertyChanging("MaBarcode");
                _MaBarcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaBarcode");
                OnMaBarcodeChanged();
            }
        }
        private global::System.String _MaBarcode;
        partial void OnMaBarcodeChanging(global::System.String value);
        partial void OnMaBarcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ThoiGian
        {
            get
            {
                return _ThoiGian;
            }
            set
            {
                OnThoiGianChanging(value);
                ReportPropertyChanging("ThoiGian");
                _ThoiGian = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThoiGian");
                OnThoiGianChanged();
            }
        }
        private Nullable<global::System.DateTime> _ThoiGian;
        partial void OnThoiGianChanging(Nullable<global::System.DateTime> value);
        partial void OnThoiGianChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLuong
        {
            get
            {
                return _SoLuong;
            }
            set
            {
                OnSoLuongChanging(value);
                ReportPropertyChanging("SoLuong");
                _SoLuong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoLuong");
                OnSoLuongChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLuong;
        partial void OnSoLuongChanging(Nullable<global::System.Int32> value);
        partial void OnSoLuongChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblKetQuaSX_tblSanPham", "tblSanPham")]
        public tblSanPham tblSanPham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblKetQuaSX_tblSanPham", "tblSanPham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblKetQuaSX_tblSanPham", "tblSanPham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblSanPham> tblSanPhamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblKetQuaSX_tblSanPham", "tblSanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblSanPham>("THACOModel.FK_tblKetQuaSX_tblSanPham", "tblSanPham", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblLoaiSP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblLoaiSP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblLoaiSP object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblLoaiSP CreatetblLoaiSP(global::System.Int32 id)
        {
            tblLoaiSP tblLoaiSP = new tblLoaiSP();
            tblLoaiSP.ID = id;
            return tblLoaiSP;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaLoaiSP
        {
            get
            {
                return _MaLoaiSP;
            }
            set
            {
                OnMaLoaiSPChanging(value);
                ReportPropertyChanging("MaLoaiSP");
                _MaLoaiSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaLoaiSP");
                OnMaLoaiSPChanged();
            }
        }
        private global::System.String _MaLoaiSP;
        partial void OnMaLoaiSPChanging(global::System.String value);
        partial void OnMaLoaiSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLoaiSP
        {
            get
            {
                return _TenLoaiSP;
            }
            set
            {
                OnTenLoaiSPChanging(value);
                ReportPropertyChanging("TenLoaiSP");
                _TenLoaiSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLoaiSP");
                OnTenLoaiSPChanged();
            }
        }
        private global::System.String _TenLoaiSP;
        partial void OnTenLoaiSPChanging(global::System.String value);
        partial void OnTenLoaiSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DonViID
        {
            get
            {
                return _DonViID;
            }
            set
            {
                OnDonViIDChanging(value);
                ReportPropertyChanging("DonViID");
                _DonViID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DonViID");
                OnDonViIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DonViID;
        partial void OnDonViIDChanging(Nullable<global::System.Int32> value);
        partial void OnDonViIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblLoaiSP_tblDonVi", "tblDonVi")]
        public tblDonVi tblDonVi
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblDonVi>("THACOModel.FK_tblLoaiSP_tblDonVi", "tblDonVi").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblDonVi>("THACOModel.FK_tblLoaiSP_tblDonVi", "tblDonVi").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblDonVi> tblDonViReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblDonVi>("THACOModel.FK_tblLoaiSP_tblDonVi", "tblDonVi");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblDonVi>("THACOModel.FK_tblLoaiSP_tblDonVi", "tblDonVi", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblSanPham_tblLoaiSP", "tblSanPham")]
        public EntityCollection<tblSanPham> tblSanPhams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSanPham>("THACOModel.FK_tblSanPham_tblLoaiSP", "tblSanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSanPham>("THACOModel.FK_tblSanPham_tblLoaiSP", "tblSanPham", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblSanPham")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSanPham : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSanPham object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblSanPham CreatetblSanPham(global::System.Int32 id)
        {
            tblSanPham tblSanPham = new tblSanPham();
            tblSanPham.ID = id;
            return tblSanPham;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaSanPham
        {
            get
            {
                return _MaSanPham;
            }
            set
            {
                OnMaSanPhamChanging(value);
                ReportPropertyChanging("MaSanPham");
                _MaSanPham = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaSanPham");
                OnMaSanPhamChanged();
            }
        }
        private global::System.String _MaSanPham;
        partial void OnMaSanPhamChanging(global::System.String value);
        partial void OnMaSanPhamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenSanPham
        {
            get
            {
                return _TenSanPham;
            }
            set
            {
                OnTenSanPhamChanging(value);
                ReportPropertyChanging("TenSanPham");
                _TenSanPham = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenSanPham");
                OnTenSanPhamChanged();
            }
        }
        private global::System.String _TenSanPham;
        partial void OnTenSanPhamChanging(global::System.String value);
        partial void OnTenSanPhamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LoaiSPID
        {
            get
            {
                return _LoaiSPID;
            }
            set
            {
                OnLoaiSPIDChanging(value);
                ReportPropertyChanging("LoaiSPID");
                _LoaiSPID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoaiSPID");
                OnLoaiSPIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LoaiSPID;
        partial void OnLoaiSPIDChanging(Nullable<global::System.Int32> value);
        partial void OnLoaiSPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KyHieuNhan
        {
            get
            {
                return _KyHieuNhan;
            }
            set
            {
                OnKyHieuNhanChanging(value);
                ReportPropertyChanging("KyHieuNhan");
                _KyHieuNhan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KyHieuNhan");
                OnKyHieuNhanChanged();
            }
        }
        private global::System.String _KyHieuNhan;
        partial void OnKyHieuNhanChanging(global::System.String value);
        partial void OnKyHieuNhanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QuyCach
        {
            get
            {
                return _QuyCach;
            }
            set
            {
                OnQuyCachChanging(value);
                ReportPropertyChanging("QuyCach");
                _QuyCach = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QuyCach");
                OnQuyCachChanged();
            }
        }
        private global::System.String _QuyCach;
        partial void OnQuyCachChanging(global::System.String value);
        partial void OnQuyCachChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblBaoCaoSX_tblSanPham", "tblBaoCaoSX")]
        public EntityCollection<tblBaoCaoSX> tblBaoCaoSXes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblBaoCaoSX>("THACOModel.FK_tblBaoCaoSX_tblSanPham", "tblBaoCaoSX");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblBaoCaoSX>("THACOModel.FK_tblBaoCaoSX_tblSanPham", "tblBaoCaoSX", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblKeHoachSX_tblSanPham", "tblKeHoachSX")]
        public EntityCollection<tblKeHoachSX> tblKeHoachSXes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblKeHoachSX>("THACOModel.FK_tblKeHoachSX_tblSanPham", "tblKeHoachSX");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblKeHoachSX>("THACOModel.FK_tblKeHoachSX_tblSanPham", "tblKeHoachSX", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblKetQuaSX_tblSanPham", "tblKetQuaSX")]
        public EntityCollection<tblKetQuaSX> tblKetQuaSXes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblKetQuaSX>("THACOModel.FK_tblKetQuaSX_tblSanPham", "tblKetQuaSX");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblKetQuaSX>("THACOModel.FK_tblKetQuaSX_tblSanPham", "tblKetQuaSX", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblSanPham_tblLoaiSP", "tblLoaiSP")]
        public tblLoaiSP tblLoaiSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLoaiSP>("THACOModel.FK_tblSanPham_tblLoaiSP", "tblLoaiSP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLoaiSP>("THACOModel.FK_tblSanPham_tblLoaiSP", "tblLoaiSP").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblLoaiSP> tblLoaiSPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLoaiSP>("THACOModel.FK_tblSanPham_tblLoaiSP", "tblLoaiSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblLoaiSP>("THACOModel.FK_tblSanPham_tblLoaiSP", "tblLoaiSP", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblTaoMa_tblSanPham", "tblTaoMa")]
        public EntityCollection<tblTaoMa> tblTaoMas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblTaoMa>("THACOModel.FK_tblTaoMa_tblSanPham", "tblTaoMa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblTaoMa>("THACOModel.FK_tblTaoMa_tblSanPham", "tblTaoMa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblTaoMa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTaoMa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTaoMa object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblTaoMa CreatetblTaoMa(global::System.Int32 id)
        {
            tblTaoMa tblTaoMa = new tblTaoMa();
            tblTaoMa.ID = id;
            return tblTaoMa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SanPhamID
        {
            get
            {
                return _SanPhamID;
            }
            set
            {
                OnSanPhamIDChanging(value);
                ReportPropertyChanging("SanPhamID");
                _SanPhamID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SanPhamID");
                OnSanPhamIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SanPhamID;
        partial void OnSanPhamIDChanging(Nullable<global::System.Int32> value);
        partial void OnSanPhamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KyHieuNhan
        {
            get
            {
                return _KyHieuNhan;
            }
            set
            {
                OnKyHieuNhanChanging(value);
                ReportPropertyChanging("KyHieuNhan");
                _KyHieuNhan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KyHieuNhan");
                OnKyHieuNhanChanged();
            }
        }
        private global::System.String _KyHieuNhan;
        partial void OnKyHieuNhanChanging(global::System.String value);
        partial void OnKyHieuNhanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NamSX
        {
            get
            {
                return _NamSX;
            }
            set
            {
                OnNamSXChanging(value);
                ReportPropertyChanging("NamSX");
                _NamSX = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NamSX");
                OnNamSXChanged();
            }
        }
        private global::System.String _NamSX;
        partial void OnNamSXChanging(global::System.String value);
        partial void OnNamSXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThangSX
        {
            get
            {
                return _ThangSX;
            }
            set
            {
                OnThangSXChanging(value);
                ReportPropertyChanging("ThangSX");
                _ThangSX = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThangSX");
                OnThangSXChanged();
            }
        }
        private global::System.String _ThangSX;
        partial void OnThangSXChanging(global::System.String value);
        partial void OnThangSXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Ngay
        {
            get
            {
                return _Ngay;
            }
            set
            {
                OnNgayChanging(value);
                ReportPropertyChanging("Ngay");
                _Ngay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ngay");
                OnNgayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Ngay;
        partial void OnNgayChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoLuong
        {
            get
            {
                return _SoLuong;
            }
            set
            {
                OnSoLuongChanging(value);
                ReportPropertyChanging("SoLuong");
                _SoLuong = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SoLuong");
                OnSoLuongChanged();
            }
        }
        private global::System.String _SoLuong;
        partial void OnSoLuongChanging(global::System.String value);
        partial void OnSoLuongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaBarcode
        {
            get
            {
                return _MaBarcode;
            }
            set
            {
                OnMaBarcodeChanging(value);
                ReportPropertyChanging("MaBarcode");
                _MaBarcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaBarcode");
                OnMaBarcodeChanged();
            }
        }
        private global::System.String _MaBarcode;
        partial void OnMaBarcodeChanging(global::System.String value);
        partial void OnMaBarcodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("THACOModel", "FK_tblTaoMa_tblSanPham", "tblSanPham")]
        public tblSanPham tblSanPham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblTaoMa_tblSanPham", "tblSanPham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblTaoMa_tblSanPham", "tblSanPham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblSanPham> tblSanPhamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSanPham>("THACOModel.FK_tblTaoMa_tblSanPham", "tblSanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblSanPham>("THACOModel.FK_tblTaoMa_tblSanPham", "tblSanPham", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblThamSo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblThamSo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblThamSo object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblThamSo CreatetblThamSo(global::System.Int32 id)
        {
            tblThamSo tblThamSo = new tblThamSo();
            tblThamSo.ID = id;
            return tblThamSo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Kyhieu
        {
            get
            {
                return _Kyhieu;
            }
            set
            {
                OnKyhieuChanging(value);
                ReportPropertyChanging("Kyhieu");
                _Kyhieu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Kyhieu");
                OnKyhieuChanged();
            }
        }
        private global::System.String _Kyhieu;
        partial void OnKyhieuChanging(global::System.String value);
        partial void OnKyhieuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GiaTri
        {
            get
            {
                return _GiaTri;
            }
            set
            {
                OnGiaTriChanging(value);
                ReportPropertyChanging("GiaTri");
                _GiaTri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GiaTri");
                OnGiaTriChanged();
            }
        }
        private global::System.String _GiaTri;
        partial void OnGiaTriChanging(global::System.String value);
        partial void OnGiaTriChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="THACOModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUser object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblUser CreatetblUser(global::System.Int32 id)
        {
            tblUser tblUser = new tblUser();
            tblUser.ID = id;
            return tblUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DislayName
        {
            get
            {
                return _DislayName;
            }
            set
            {
                OnDislayNameChanging(value);
                ReportPropertyChanging("DislayName");
                _DislayName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DislayName");
                OnDislayNameChanged();
            }
        }
        private global::System.String _DislayName;
        partial void OnDislayNameChanging(global::System.String value);
        partial void OnDislayNameChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="THACOModel", Name="KetQua_Ngay_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class KetQua_Ngay_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KetQua_Ngay_Result object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="sanPhamID">Initial value of the SanPhamID property.</param>
        public static KetQua_Ngay_Result CreateKetQua_Ngay_Result(global::System.Int32 id, global::System.Int32 sanPhamID)
        {
            KetQua_Ngay_Result ketQua_Ngay_Result = new KetQua_Ngay_Result();
            ketQua_Ngay_Result.ID = id;
            ketQua_Ngay_Result.SanPhamID = sanPhamID;
            return ketQua_Ngay_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SanPhamID
        {
            get
            {
                return _SanPhamID;
            }
            set
            {
                OnSanPhamIDChanging(value);
                ReportPropertyChanging("SanPhamID");
                _SanPhamID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SanPhamID");
                OnSanPhamIDChanged();
            }
        }
        private global::System.Int32 _SanPhamID;
        partial void OnSanPhamIDChanging(global::System.Int32 value);
        partial void OnSanPhamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaSanPham
        {
            get
            {
                return _MaSanPham;
            }
            set
            {
                OnMaSanPhamChanging(value);
                ReportPropertyChanging("MaSanPham");
                _MaSanPham = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaSanPham");
                OnMaSanPhamChanged();
            }
        }
        private global::System.String _MaSanPham;
        partial void OnMaSanPhamChanging(global::System.String value);
        partial void OnMaSanPhamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenSanPham
        {
            get
            {
                return _TenSanPham;
            }
            set
            {
                OnTenSanPhamChanging(value);
                ReportPropertyChanging("TenSanPham");
                _TenSanPham = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenSanPham");
                OnTenSanPhamChanged();
            }
        }
        private global::System.String _TenSanPham;
        partial void OnTenSanPhamChanging(global::System.String value);
        partial void OnTenSanPhamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LoaiSPID
        {
            get
            {
                return _LoaiSPID;
            }
            set
            {
                OnLoaiSPIDChanging(value);
                ReportPropertyChanging("LoaiSPID");
                _LoaiSPID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoaiSPID");
                OnLoaiSPIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LoaiSPID;
        partial void OnLoaiSPIDChanging(Nullable<global::System.Int32> value);
        partial void OnLoaiSPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaLoaiSP
        {
            get
            {
                return _MaLoaiSP;
            }
            set
            {
                OnMaLoaiSPChanging(value);
                ReportPropertyChanging("MaLoaiSP");
                _MaLoaiSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaLoaiSP");
                OnMaLoaiSPChanged();
            }
        }
        private global::System.String _MaLoaiSP;
        partial void OnMaLoaiSPChanging(global::System.String value);
        partial void OnMaLoaiSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLoaiSP
        {
            get
            {
                return _TenLoaiSP;
            }
            set
            {
                OnTenLoaiSPChanging(value);
                ReportPropertyChanging("TenLoaiSP");
                _TenLoaiSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLoaiSP");
                OnTenLoaiSPChanged();
            }
        }
        private global::System.String _TenLoaiSP;
        partial void OnTenLoaiSPChanging(global::System.String value);
        partial void OnTenLoaiSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KeHoachNgay
        {
            get
            {
                return _KeHoachNgay;
            }
            set
            {
                OnKeHoachNgayChanging(value);
                ReportPropertyChanging("KeHoachNgay");
                _KeHoachNgay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KeHoachNgay");
                OnKeHoachNgayChanged();
            }
        }
        private Nullable<global::System.Int32> _KeHoachNgay;
        partial void OnKeHoachNgayChanging(Nullable<global::System.Int32> value);
        partial void OnKeHoachNgayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThucHienNgay
        {
            get
            {
                return _ThucHienNgay;
            }
            set
            {
                OnThucHienNgayChanging(value);
                ReportPropertyChanging("ThucHienNgay");
                _ThucHienNgay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThucHienNgay");
                OnThucHienNgayChanged();
            }
        }
        private Nullable<global::System.Int32> _ThucHienNgay;
        partial void OnThucHienNgayChanging(Nullable<global::System.Int32> value);
        partial void OnThucHienNgayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ChenhLech
        {
            get
            {
                return _ChenhLech;
            }
            set
            {
                OnChenhLechChanging(value);
                ReportPropertyChanging("ChenhLech");
                _ChenhLech = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChenhLech");
                OnChenhLechChanged();
            }
        }
        private Nullable<global::System.Int32> _ChenhLech;
        partial void OnChenhLechChanging(Nullable<global::System.Int32> value);
        partial void OnChenhLechChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KeHoachThang
        {
            get
            {
                return _KeHoachThang;
            }
            set
            {
                OnKeHoachThangChanging(value);
                ReportPropertyChanging("KeHoachThang");
                _KeHoachThang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KeHoachThang");
                OnKeHoachThangChanged();
            }
        }
        private Nullable<global::System.Int32> _KeHoachThang;
        partial void OnKeHoachThangChanging(Nullable<global::System.Int32> value);
        partial void OnKeHoachThangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KetQuaThang
        {
            get
            {
                return _KetQuaThang;
            }
            set
            {
                OnKetQuaThangChanging(value);
                ReportPropertyChanging("KetQuaThang");
                _KetQuaThang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KetQuaThang");
                OnKetQuaThangChanged();
            }
        }
        private Nullable<global::System.Int32> _KetQuaThang;
        partial void OnKetQuaThangChanging(Nullable<global::System.Int32> value);
        partial void OnKetQuaThangChanged();

        #endregion
    }

    #endregion
    
}
